name: WebpackReact
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    types:
      - opened

jobs:
  lint:
    runs-on: ubuntu-latest
    name: eslint
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn lint

  typecheck:
    runs-on: ubuntu-latest  # 指定操作系统
    name: typecheck
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn typecheck
